version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: ./app  # Dockerfile for Flask app should be in ./app directory
    environment:
      FLASK_APP: app.py
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: my_database
      REDIS_HOST: redis
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
