services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .  # Use the current directory as the build context if the Dockerfile is in the project root.
    environment:
      FLASK_APP: app.py
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: mydatabase
      REDIS_HOST: redis
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
