version: '3'

services:
  app:
    build: .
    ports:
      - "80:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_DB=users_db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
