name: Deploy to HTTP Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        server: ["10.0.2.102", "10.0.2.101"]  # Using IP addresses directly

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin <<< "${{ secrets.DOCKERHUB_PASSWORD }}"

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest

    - name: Deploy Docker container
      env:
        SSH_BASTION_KEY: ${{ secrets.SSH_BASTION }}
      run: |
        # Save the SSH bastion key to a file and set appropriate permissions
        echo "$SSH_BASTION_KEY" > bastion_key.pem
        chmod 600 bastion_key.pem
        
        # Use SSH to connect through the bastion host
        ssh -o ProxyCommand="ssh -i bastion_key.pem -W %h:%p user@bastion_ip_address" user@${{ matrix.server }} <<'EOF'
          docker run -d \
            --name app \
            -p 80:5000 \
            -e REDIS_HOST=redis \
            -e DB_NAME=mydatabase \
            -e DB_PASSWORD=password \
            -e DB_USER=user \
            -e DB_HOST=db \
            ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest
        EOF
